services:
  db:
    image: postgres:18
    container_name: jobetl-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jobetl_user
      POSTGRES_PASSWORD: secure_password_here
      POSTGRES_DB: jobetl
    volumes:
      - jobetl_postgres_data:/var/lib/postgresql
      - ./data/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

volumes:
  jobetl_postgres_data:
    name: jobetl_postgres_data
